### ISSUE TITLE
Can I use react-loadable-visibility?

### ISSUE THREAD

**Issue by eugle** [CaptainN/npdev-react-loadable#11]
How does he use it, thank you!

I found that it was so integrated that it had nothing to do with npdev-reacty-loadable, so does that mean it's not available

![image](https://user-images.githubusercontent.com/24447931/80172049-82cf8380-861e-11ea-83f5-94b6fcc5b3a5.png)

**Comment by CaptainN** [comment]
I'm not familiar with `@loadable/component`. It looks like an alternative to the older `react-loadable` component, on which my package is based.

`npdev:react-loadable` is a package for Meteor (and delivered through atmosphere.js), and won't be useful for projects build on other platforms.

**Comment by CaptainN** [comment]
As far as using `react-loadable-visibility` you'd have to fork it, and modify it slightly:

```js
import React, { Component } from 'react'
import Loadable from 'meteor/npdev:react-loadable' // change this
import createLoadableVisibilityComponent from './createLoadableVisibilityComponent'
import { IntersectionObserver } from './capacities'

function LoadableVisibility (opts) {
  if (IntersectionObserver) {
    return createLoadableVisibilityComponent([opts], {
      Loadable,
      preloadFunc: 'preload',
      LoadingComponent: opts.loading,
    })
  } else {
    return Loadable(opts)
  }
}

function LoadableVisibilityMap (opts) {
  if (IntersectionObserver) {
    return createLoadableVisibilityComponent([opts], {
      Loadable: Loadable.Map,
      preloadFunc: 'preload',
      LoadingComponent: opts.loading,
    })
  } else {
    return Loadable.Map(opts)
  }
}

LoadableVisibility.Map = LoadableVisibilityMap

export LoadableVisibility
```

I make no guarantees that'll work though. Maybe ask the author if they'd like to support `npdev:react-loadable`? They could either release an atmosphere package, or keep in npm but add some instructions (to use an npm package that relies on atmosphere packages, you'd have to add the package to meteor's recompile configuration, so that it can import the package, and get modern bundle benefits, etc.).

**Comment by eugle** [comment]
Thank you very much. I won't consider using it for the moment. Split ends are difficult for me
