### ISSUE TITLE
Good/Bad idea to add subscriptions in the LoadableMap?

### ISSUE THREAD

**Issue by cosio55** [CaptainN/npdev-react-loadable#5]
Hi, first of all thanks for porting this amazing library for Meteor!

I'm starting to refactor my app around Loadable Components and just started with the routes, went from around 9MB to 6MB and time to first interaction from 12s to 3.5s so amazing results and all without even using the production flag. I wanted to ask, would you think it's a good idea to add the different subscriptions inside a 'LoadableMap', so that whenever the 'Loading' finishes the user has all the relevant data needed?

**Comment by CaptainN** [comment]
To be honest, I don't use `LoadableMap` at all, so I'm not familiar with it. I tend to set up my subscriptions in the actual loaded components. I suppose you could do a sort of Loadable container idea. You are after, I gather, some parallel loading? You could do that at component definition like this:

```js
const MyContentLoadable = Loadable({
  loader: () => import('./ui/MyContent'),
  loading: Loading
})
const MyContent = withTracker((props) => {
  return { subscription: Meteor.subscribe('my-pub') }
})
```

Then you can use the `MyContent` component in your routes or whatever, instead of the Loadable component. It should be similar with `LoadableMap` and as many subscriptions as you need.
